### ISSUE TITLE
Add support for other extensions

### ISSUE THREAD

**Issue by devmattrick** [chocolateboy/parcel-plugin-nunjucks#2]
As a standard, Nunjucks has adopted `.njk` as an extension, however there are some people who may be using other extensions such as `.nunjucks` or even `.html`. I'm not exactly sure how to handle this sort of issue.-

**Comment by chocolateboy** [comment]
Another issue/possibility: the plugin currently delegates to HTMLAsset in all cases, which means it only works with HTML templates, but there are plenty of other uses for nunjucks templating e.g. plain text, Markdown, JavaScript etc.

Assuming Parcel provides a way to map an extension back to its asset handler, optional support for dual extensions could work well e.g.:

- .njk.html (or .html.njk) -> NunjucksAsset -> HTMLAsset
- .njk.json -> NunjucksAsset -> JSONAsset

etc.

**Comment by chocolateboy** [comment]
We could add `.nunjucks` (and `.nj`) as an alias for `.njk`, though I'm not sure it's worth it since the nunjucks [recommends/advises using `.njk`](https://mozilla.github.io/nunjucks/templating.html#file-extensions).

A unique extension is required by Parcel (v1 at least), so we can't do e.g. `index.njk.html`. But we can support templates for other filetypes e.g. `foo.js.njk`, `bar.json.njk` etc. as suggested above, rather than just HTML (though it remains the default).

I have this working locally. Just gotta figure out how to write Parcel tests. It's a breaking change though, so it'll have to wait for v2.

**Comment by chocolateboy** [comment]
We could add `.nunjucks` (and `.nj`) as an alias for `.njk`, though I'm not sure it's worth it since the nunjucks docs [recommend/advise using `.njk`](https://mozilla.github.io/nunjucks/templating.html#file-extensions).

**Comment by chocolateboy** [comment]
Closing this as `.njk` is the standard and it's clearer than hijacking an existing extension like `.html`, even if that were possible.
